### ISSUE TITLE
AST-to-JS?

### ISSUE THREAD

**Issue by Pomax** [mazko/jsjavaparser#10]
Is there any project that you've written, or that you know of written by others, that can convert the resulting AST into JavaScript? This project might allow porting quite a few "Java source" languages such as Processing to a web-executable format (I've worked on Processing.js but its parser is too clever to maintain), but a necessary start would be to be able to convert the AST into runnable Javascript (either directly, AST-to-JS-object, or indirectly, as AST-to-JS-source-code).

I've stubbed a small test over on https://github.com/Pomax/java-parser-test but if there are AST-to-JS solutions already, I'd really much prefer not rolling my own =)

**Comment by mazko** [comment]
Maybe http://mazko.github.io/ESJava/ |  https://github.com/tomitrescak/Transpiler

**Comment by Pomax** [comment]
the latter has 0 documentation, but your ESJava looks very interesting! Thanks!
