### ISSUE TITLE
Javascript Crash

### ISSUE THREAD

**Issue by Hugheth** [mazko/jsjavaparser#2]
When parsing nested parentheses, rather than throwing an error the parser crashes the current Javascript environment (e.g. on the demo it crashes the browser tab)

```
package js.java.parser;

import static java.lang.System.out;

import java.util.*;

public class HelloWorld {
  public static void main(final String[] args) {

        ( ( ) )

  }
}
```

**Comment by mazko** [comment]
wow, thanks !

**Comment by Hugheth** [comment]
Not sure if it was a bug with the grammar or PEG.js but I'm guessing PEG shouldn't allow grammars to do this anyway, so I've submitted a bug upstream to PEG and will post any fixes. https://github.com/pegjs/pegjs/issues/377

Interestingly, I extended your grammar to include lambda expressions, and with that inclusion instead of crashing the above example merely locks up the parser for a second or so. https://github.com/Hugheth/jsjavaparser

**Comment by mazko** [comment]
So let's try clean grammar https://raw.githubusercontent.com/mazko/jsjavaparser/5bc9ff08afb07f010ac8d43145b8f1cc5b061662/src/Java.1.7.pegjs and test it http://pegjs.org/online

There is error parsing `( ( ) )`, `( ( ) );` and i think such behaviour is correct. So looks more like a bug somewhere in grammar or post AST build implementation  (eclipse like), **not PEG.js** bug. May by infinite loop e.t.c. I thin compare https://raw.githubusercontent.com/mazko/jsjavaparser/5bc9ff08afb07f010ac8d43145b8f1cc5b061662/src/Java.1.7.pegjs and https://github.com/mazko/jsjavaparser/blob/master/src/Java.1.7.pegjs is the best point to start from.

**Comment by Hugheth** [comment]
Hi Mazko,

I can confirm the initial commit without the implementation doesn't reproduce this crash, so I will try and look for problems with the implementation.

Cheers

**Comment by mazko** [comment]
Can't reproduce after pegjs update 0.10. Code below reports parser error from now.

```
package js.java.parser;

import static java.lang.System.out;

import java.util.*;

public class HelloWorld {
  public static void main(final String[] args) {
        ((;));
  }
}
```

`javac` has same behaviour. Fixed ?
