### ISSUE TITLE
Problem with ID

### ISSUE THREAD

**Issue by BrianCapone** [mazko/jsjavaparser#8]
Heyho,

first let me say thank you really really much for the jsjavaparser, it's great!
I use it for a bachelor thesis prototype. 
I got one problem: The editor will only be implemented if the ID equals "editor". I need 2 Editors in one single HTML Page. I tried to fix it but was unable to do so, since i'm not a professional. 

I would appreciate any help I could get

**Comment by mazko** [comment]
Hi. If I remember correctly I used this editor https://wiki.eclipse.org/Orion/How_Tos/Code_Edit

Download http://download.eclipse.org/orion/ and run examples.

Orion forum http://www.eclipse.org/forums/index.php?t=thread&frm_id=227

**Comment by BrianCapone** [comment]
I managed to enable multiple editors in one html page, but the parsing is not working anymore. The problem is, that I can't run the window.editor.getText() - method anymore.

**This is my onload function in the file parse.js:**

 window.onload = function () {
            require(["orion/editor/edit"], function(edit) {
           var editor = edit({className: "editor"});
           editor.getTextView().getModel().addEventListener("Changed", function () { parse(); });
           parse(42);  
        });

**This is the parse function as you wrote it:**

```
function parse(delay) {
    if (parseId) {
        window.clearTimeout(parseId);
    }

    parseId = window.setTimeout(function () {
        var code, result, str;

        _code = window.editor.getText();_ **// here is the problem**
        id('info').className = 'alert-box secondary';

        try { ...
```

---

i tried to get the editor with $("editor").editor.gettext() and a lot of different approaches for hours, but it won't work! Maybe you got an idea how i could get the text of my editor :/
Error message is : Cannot read property 'getText' of undefined

Thanks!
