### ISSUE TITLE
Exponential complexity of nested functions

### ISSUE THREAD

**Issue by tomitrescak** [mazko/jsjavaparser#9]
Could you please give me a pointer how can I solve a problem with exponential complexity of nested function calls?

Example:

b(3); // blazing fast
b(c(3)) // slower
b(c(d(e))) // couple seconds
b(c(d(e(f)))) //minute
...
6 and more ... will probably never finish in this time ;(

**Comment by mazko** [comment]
- please provide Java source which causes a problem
- try pegs --cache option
- #2 can be relevant to this problem https://github.com/pegjs/pegjs/issues/377

**Comment by tomitrescak** [comment]
Hi, here is an example

```
class A {
void b() {
  c(d(e(f()));
}
}
```

This will finish, but will take a lot of time to complete ;( one more nesting and i will take minutes.
Any help would be greatly appreciated. Otherwise this project saved me a lot of pain. Thank you for it!

**Comment by tomitrescak** [comment]
Ha! The --cache option worked!!!! Thanks!!

You just gotta love when solution is one command line parameter away! 👍
